apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tacocat
    service: loadgen
  name: loadgen
  namespace: tacocat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tacocat
      service: loadgen
  template:
    metadata:
      labels:
        app: tacocat
        service: loadgen
    spec:
      containers:
      - name: loadgen
        image: dambott/x64loadgen:latest
        imagePullPolicy: Always
        command:
        - "java"
        - "-javaagent:opentelemetry-javaagent.jar"
        - "-Dotel.javaagent.configuration-file=/otel/loadgen.properties"
        - "-jar"
        - "/loadgen.jar"
        - "shopping"
        - "50050"
        - "50051"
        - "2"
        - "15"
        - "0"
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
        volumeMounts:
           - name: otel
             mountPath: /otel
      volumes:
         - name: otel
           configMap:
             name: otel-config
             defaultMode: 0744

